language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: py.test --cov=./flask_gtts/ test_fg.py
after_success:
  - coveralls